sudo: false
language: python
env:
  - TOXENV=py27-dj18
  - TOXENV=py33-dj18
  - TOXENV=py34-dj18
  - TOXENV=py35-dj18
  - TOXENV=pypy-dj18
  - TOXENV=py27-dj19
  - TOXENV=py34-dj19
  - TOXENV=py35-dj19
  - TOXENV=flake8
install:
  - travis_retry pip install tox
script: tox
